#file: noinspection ComposeUnknownKeys
include:
  - environment-compose.yml

services:
  app:
    build:
      dockerfile: project.Dockerfile
    container_name: main_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_CONTAINER_NAME: $POSTGRES_CONTAINER_NAME
      JWT_SECRET: $JWT_SECRET
    depends_on:
      liquibase-migrations:
        condition: service_completed_successfully
      postgresql:
        condition: service_healthy
    networks:
      - backend
