global:
  scrape_interval: 5s
  external_labels:
    monitor: 'caselab-monitor'

scrape_configs:
  - job_name: 'project_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
